/**
 * Claude Provider 预设配置
 * 从 cc-switch 提取的主流供应商配置
 */

import { ClaudeProviderPreset } from '@/types/provider'

export const claudeProviderPresets: ClaudeProviderPreset[] = [
  {
    id: 'claude-official',
    name: 'Claude Official',
    category: 'official',
    websiteUrl: 'https://www.anthropic.com/claude-code',
    description: 'Anthropic 官方 API',
    icon: 'anthropic',
    iconColor: '#D4915D',
    config: {
      env: {
        ANTHROPIC_BASE_URL: 'https://api.deepseek.com/v1',
        ANTHROPIC_AUTH_TOKEN: '',
      },
    },
  },
  {
    id: 'custom',
    name: 'Custom Provider',
    category: 'custom',
    websiteUrl: '',
    description: '自定义供应商配置',
    config: {
      env: {
        ANTHROPIC_BASE_URL: '',
        ANTHROPIC_AUTH_TOKEN: '',
      },
    },
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    category: 'cn_official',
    websiteUrl: 'https://platform.deepseek.com',
    description: 'DeepSeek 官方 API',
    icon: 'deepseek',
    iconColor: '#1E88E5',
    config: {
      env: {
        ANTHROPIC_BASE_URL: 'https://api.deepseek.com/anthropic',
        ANTHROPIC_AUTH_TOKEN: '',
        ANTHROPIC_MODEL: 'DeepSeek-V3.2',
        ANTHROPIC_DEFAULT_HAIKU_MODEL: 'DeepSeek-V3.2',
        ANTHROPIC_DEFAULT_SONNET_MODEL: 'DeepSeek-V3.2',
        ANTHROPIC_DEFAULT_OPUS_MODEL: 'DeepSeek-V3.2',
      },
    },
  },
  {
    id: 'zhipu-glm',
    name: 'Zhipu GLM',
    category: 'cn_official',
    websiteUrl: 'https://open.bigmodel.cn',
    apiKeyUrl: 'https://www.bigmodel.cn/claude-code',
    description: '智谱 GLM 官方 API',
    icon: 'zhipu',
    iconColor: '#0F62FE',
    isPartner: true,
    config: {
      env: {
        ANTHROPIC_BASE_URL: 'https://open.bigmodel.cn/api/anthropic',
        ANTHROPIC_AUTH_TOKEN: '',
        ANTHROPIC_MODEL: 'glm-4.7',
        ANTHROPIC_DEFAULT_HAIKU_MODEL: 'glm-4.7',
        ANTHROPIC_DEFAULT_SONNET_MODEL: 'glm-4.7',
        ANTHROPIC_DEFAULT_OPUS_MODEL: 'glm-4.7',
      },
    },
  },
  {
    id: 'kimi',
    name: 'Kimi',
    category: 'cn_official',
    websiteUrl: 'https://platform.moonshot.cn/console',
    description: 'Moonshot Kimi 官方 API',
    icon: 'kimi',
    iconColor: '#6366F1',
    config: {
      env: {
        ANTHROPIC_BASE_URL: 'https://api.moonshot.cn/anthropic',
        ANTHROPIC_AUTH_TOKEN: '',
        ANTHROPIC_MODEL: 'kimi-k2.5',
        ANTHROPIC_DEFAULT_HAIKU_MODEL: 'kimi-k2.5',
        ANTHROPIC_DEFAULT_SONNET_MODEL: 'kimi-k2.5',
        ANTHROPIC_DEFAULT_OPUS_MODEL: 'kimi-k2.5',
      },
    },
  },
  {
    id: 'kimi-coding',
    name: 'Kimi For Coding',
    category: 'cn_official',
    websiteUrl: 'https://www.kimi.com/coding/docs/',
    description: 'Kimi 专用编程 API',
    icon: 'kimi',
    iconColor: '#6366F1',
    config: {
      env: {
        ANTHROPIC_BASE_URL: 'https://api.kimi.com/coding/',
        ANTHROPIC_AUTH_TOKEN: '',
      },
    },
  },
  {
    id: 'bailian',
    name: 'Bailian',
    category: 'cn_official',
    websiteUrl: 'https://bailian.console.aliyun.com',
    description: '阿里云百炼平台',
    icon: 'bailian',
    iconColor: '#624AFF',
    config: {
      env: {
        ANTHROPIC_BASE_URL: 'https://dashscope.aliyuncs.com/apps/anthropic',
        ANTHROPIC_AUTH_TOKEN: '',
      },
    },
  },
  {
    id: 'modelscope',
    name: 'ModelScope',
    category: 'aggregator',
    websiteUrl: 'https://modelscope.cn',
    description: '魔搭社区 API',
    icon: 'modelscope',
    iconColor: '#624AFF',
    config: {
      env: {
        ANTHROPIC_BASE_URL: 'https://api-inference.modelscope.cn',
        ANTHROPIC_AUTH_TOKEN: '',
        ANTHROPIC_MODEL: 'ZhipuAI/GLM-4.7',
        ANTHROPIC_DEFAULT_HAIKU_MODEL: 'ZhipuAI/GLM-4.7',
        ANTHROPIC_DEFAULT_SONNET_MODEL: 'ZhipuAI/GLM-4.7',
        ANTHROPIC_DEFAULT_OPUS_MODEL: 'ZhipuAI/GLM-4.7',
      },
    },
  },
  {
    id: 'kat-coder',
    name: 'KAT-Coder',
    category: 'cn_official',
    websiteUrl: 'https://console.streamlake.ai',
    apiKeyUrl: 'https://console.streamlake.ai/console/api-key',
    description: '火山引擎 KAT-Coder',
    icon: 'catcoder',
    config: {
      env: {
        ANTHROPIC_BASE_URL: 'https://vanchin.streamlake.ai/api/gateway/v1/endpoints/${ENDPOINT_ID}/claude-code-proxy',
        ANTHROPIC_AUTH_TOKEN: '',
        ANTHROPIC_MODEL: 'KAT-Coder-Pro V1',
        ANTHROPIC_DEFAULT_HAIKU_MODEL: 'KAT-Coder-Air V1',
        ANTHROPIC_DEFAULT_SONNET_MODEL: 'KAT-Coder-Pro V1',
        ANTHROPIC_DEFAULT_OPUS_MODEL: 'KAT-Coder-Pro V1',
      },
    },
  },
  {
    id: 'longcat',
    name: 'Longcat',
    category: 'cn_official',
    websiteUrl: 'https://longcat.chat/platform',
    apiKeyUrl: 'https://longcat.chat/platform/api_keys',
    description: 'Longcat 平台',
    icon: 'longcat',
    iconColor: '#29E154',
    config: {
      env: {
        ANTHROPIC_BASE_URL: 'https://api.longcat.chat/anthropic',
        ANTHROPIC_AUTH_TOKEN: '',
        ANTHROPIC_MODEL: 'LongCat-Flash-Chat',
        ANTHROPIC_DEFAULT_HAIKU_MODEL: 'LongCat-Flash-Chat',
        ANTHROPIC_DEFAULT_SONNET_MODEL: 'LongCat-Flash-Chat',
        ANTHROPIC_DEFAULT_OPUS_MODEL: 'LongCat-Flash-Chat',
        CLAUDE_CODE_MAX_OUTPUT_TOKENS: '6000',
        CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC: '1',
      },
    },
  },
  {
    id: 'zhipu-glm-en',
    name: 'Zhipu GLM en',
    category: 'cn_official',
    websiteUrl: 'https://z.ai',
    apiKeyUrl: 'https://z.ai/subscribe?ic=8JVLJQFSKB',
    description: '智谱 GLM 国际版',
    icon: 'zhipu',
    iconColor: '#0F62FE',
    isPartner: true,
    config: {
      env: {
        ANTHROPIC_BASE_URL: 'https://api.z.ai/api/anthropic',
        ANTHROPIC_AUTH_TOKEN: '',
        ANTHROPIC_MODEL: 'glm-4.7',
        ANTHROPIC_DEFAULT_HAIKU_MODEL: 'glm-4.7',
        ANTHROPIC_DEFAULT_SONNET_MODEL: 'glm-4.7',
        ANTHROPIC_DEFAULT_OPUS_MODEL: 'glm-4.7',
      },
    },
  },
  {
    id: 'minimax',
    name: 'MiniMax',
    category: 'cn_official',
    websiteUrl: 'https://platform.minimaxi.com',
    apiKeyUrl: 'https://platform.minimaxi.com/subscribe/coding-plan',
    description: 'MiniMax 官方 API',
    icon: 'minimax',
    iconColor: '#FF6B6B',
    isPartner: true,
    config: {
      env: {
        ANTHROPIC_BASE_URL: 'https://api.minimaxi.com/anthropic',
        ANTHROPIC_AUTH_TOKEN: '',
        API_TIMEOUT_MS: '3000000',
        CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC: '1',
        ANTHROPIC_MODEL: 'MiniMax-M2.1',
        ANTHROPIC_DEFAULT_SONNET_MODEL: 'MiniMax-M2.1',
        ANTHROPIC_DEFAULT_OPUS_MODEL: 'MiniMax-M2.1',
        ANTHROPIC_DEFAULT_HAIKU_MODEL: 'MiniMax-M2.1',
      },
    },
  },
  {
    id: 'minimax-en',
    name: 'MiniMax en',
    category: 'cn_official',
    websiteUrl: 'https://platform.minimax.io',
    apiKeyUrl: 'https://platform.minimax.io/subscribe/coding-plan',
    description: 'MiniMax 国际版',
    icon: 'minimax',
    iconColor: '#FF6B6B',
    isPartner: true,
    config: {
      env: {
        ANTHROPIC_BASE_URL: 'https://api.minimax.io/anthropic',
        ANTHROPIC_AUTH_TOKEN: '',
        API_TIMEOUT_MS: '3000000',
        CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC: '1',
        ANTHROPIC_MODEL: 'MiniMax-M2.1',
        ANTHROPIC_DEFAULT_SONNET_MODEL: 'MiniMax-M2.1',
        ANTHROPIC_DEFAULT_OPUS_MODEL: 'MiniMax-M2.1',
        ANTHROPIC_DEFAULT_HAIKU_MODEL: 'MiniMax-M2.1',
      },
    },
  },
  {
    id: 'doubaoseed',
    name: 'DouBaoSeed',
    category: 'cn_official',
    websiteUrl: 'https://www.volcengine.com/product/doubao',
    apiKeyUrl: 'https://www.volcengine.com/product/doubao',
    description: '字节豆包 Seed',
    icon: 'doubao',
    iconColor: '#3370FF',
    config: {
      env: {
        ANTHROPIC_BASE_URL: 'https://ark.cn-beijing.volces.com/api/coding',
        ANTHROPIC_AUTH_TOKEN: '',
        API_TIMEOUT_MS: '3000000',
        ANTHROPIC_MODEL: 'doubao-seed-code-preview-latest',
        ANTHROPIC_DEFAULT_SONNET_MODEL: 'doubao-seed-code-preview-latest',
        ANTHROPIC_DEFAULT_OPUS_MODEL: 'doubao-seed-code-preview-latest',
        ANTHROPIC_DEFAULT_HAIKU_MODEL: 'doubao-seed-code-preview-latest',
      },
    },
  },
  {
    id: 'bailing',
    name: 'BaiLing',
    category: 'cn_official',
    websiteUrl: 'https://alipaytbox.yuque.com/sxs0ba/ling/get_started',
    description: '支付宝百灵',
    config: {
      env: {
        ANTHROPIC_BASE_URL: 'https://api.tbox.cn/api/anthropic',
        ANTHROPIC_AUTH_TOKEN: '',
        ANTHROPIC_MODEL: 'Ling-1T',
        ANTHROPIC_DEFAULT_HAIKU_MODEL: 'Ling-1T',
        ANTHROPIC_DEFAULT_SONNET_MODEL: 'Ling-1T',
        ANTHROPIC_DEFAULT_OPUS_MODEL: 'Ling-1T',
      },
    },
  },
  {
    id: 'xiaomi-mimo',
    name: 'Xiaomi MiMo',
    category: 'cn_official',
    websiteUrl: 'https://platform.xiaomimimo.com',
    apiKeyUrl: 'https://platform.xiaomimimo.com/#/console/api-keys',
    description: '小米 MiMo',
    icon: 'xiaomimimo',
    iconColor: '#000000',
    config: {
      env: {
        ANTHROPIC_BASE_URL: 'https://api.xiaomimimo.com/anthropic',
        ANTHROPIC_AUTH_TOKEN: '',
        ANTHROPIC_MODEL: 'mimo-v2-flash',
        ANTHROPIC_DEFAULT_HAIKU_MODEL: 'mimo-v2-flash',
        ANTHROPIC_DEFAULT_SONNET_MODEL: 'mimo-v2-flash',
        ANTHROPIC_DEFAULT_OPUS_MODEL: 'mimo-v2-flash',
      },
    },
  },
  {
    id: 'siliconflow',
    name: 'SiliconFlow',
    category: 'aggregator',
    websiteUrl: 'https://siliconflow.cn',
    apiKeyUrl: 'https://cloud.siliconflow.cn/me/account/ak',
    description: 'SiliconFlow API 聚合平台',
    icon: 'siliconflow',
    iconColor: '#6E29F6',
    config: {
      env: {
        ANTHROPIC_BASE_URL: 'https://api.siliconflow.cn',
        ANTHROPIC_AUTH_TOKEN: '',
        ANTHROPIC_MODEL: 'Pro/MiniMaxAI/MiniMax-M2.1',
        ANTHROPIC_DEFAULT_HAIKU_MODEL: 'Pro/MiniMaxAI/MiniMax-M2.1',
        ANTHROPIC_DEFAULT_SONNET_MODEL: 'Pro/MiniMaxAI/MiniMax-M2.1',
        ANTHROPIC_DEFAULT_OPUS_MODEL: 'Pro/MiniMaxAI/MiniMax-M2.1',
      },
    },
  },
  {
    id: 'siliconflow-en',
    name: 'SiliconFlow en',
    category: 'aggregator',
    websiteUrl: 'https://siliconflow.com',
    apiKeyUrl: 'https://cloud.siliconflow.com/account/ak',
    description: 'SiliconFlow 国际版',
    icon: 'siliconflow',
    iconColor: '#000000',
    config: {
      env: {
        ANTHROPIC_BASE_URL: 'https://api.siliconflow.com',
        ANTHROPIC_AUTH_TOKEN: '',
        ANTHROPIC_MODEL: 'MiniMaxAI/MiniMax-M2.1',
        ANTHROPIC_DEFAULT_HAIKU_MODEL: 'MiniMaxAI/MiniMax-M2.1',
        ANTHROPIC_DEFAULT_SONNET_MODEL: 'MiniMaxAI/MiniMax-M2.1',
        ANTHROPIC_DEFAULT_OPUS_MODEL: 'MiniMaxAI/MiniMax-M2.1',
      },
    },
  },
  {
    id: 'aihubmix',
    name: 'AiHubMix',
    category: 'aggregator',
    websiteUrl: 'https://aihubmix.com',
    apiKeyUrl: 'https://aihubmix.com',
    description: 'AiHubMix API 聚合平台',
    icon: 'aihubmix',
    iconColor: '#006FFB',
    config: {
      env: {
        ANTHROPIC_BASE_URL: 'https://aihubmix.com',
        ANTHROPIC_API_KEY: '',
      },
    },
    endpointCandidates: ['https://aihubmix.com', 'https://api.aihubmix.com'],
  },
  {
    id: 'dmxapi',
    name: 'DMXAPI',
    category: 'aggregator',
    websiteUrl: 'https://www.dmxapi.cn',
    apiKeyUrl: 'https://www.dmxapi.cn',
    description: 'DMXAPI 聚合平台',
    isPartner: true,
    config: {
      env: {
        ANTHROPIC_BASE_URL: 'https://www.dmxapi.cn',
        ANTHROPIC_AUTH_TOKEN: '',
      },
    },
    endpointCandidates: ['https://www.dmxapi.cn', 'https://api.dmxapi.cn'],
  },
  {
    id: 'nvidia',
    name: 'Nvidia',
    category: 'aggregator',
    websiteUrl: 'https://build.nvidia.com',
    apiKeyUrl: 'https://build.nvidia.com/settings/api-keys',
    description: 'Nvidia Build 平台',
    icon: 'nvidia',
    iconColor: '#000000',
    config: {
      env: {
        ANTHROPIC_BASE_URL: 'https://integrate.api.nvidia.com',
        ANTHROPIC_AUTH_TOKEN: '',
        ANTHROPIC_MODEL: 'moonshotai/kimi-k2.5',
        ANTHROPIC_DEFAULT_HAIKU_MODEL: 'moonshotai/kimi-k2.5',
        ANTHROPIC_DEFAULT_SONNET_MODEL: 'moonshotai/kimi-k2.5',
        ANTHROPIC_DEFAULT_OPUS_MODEL: 'moonshotai/kimi-k2.5',
      },
    },
  },
  {
    id: 'openrouter',
    name: 'OpenRouter',
    category: 'aggregator',
    websiteUrl: 'https://openrouter.ai',
    apiKeyUrl: 'https://openrouter.ai/keys',
    description: 'OpenRouter API 聚合平台',
    icon: 'openrouter',
    iconColor: '#6566F1',
    config: {
      env: {
        ANTHROPIC_BASE_URL: 'https://openrouter.ai/api',
        ANTHROPIC_AUTH_TOKEN: '',
        ANTHROPIC_MODEL: 'anthropic/claude-sonnet-4.5',
        ANTHROPIC_DEFAULT_HAIKU_MODEL: 'anthropic/claude-haiku-4.5',
        ANTHROPIC_DEFAULT_SONNET_MODEL: 'anthropic/claude-sonnet-4.5',
        ANTHROPIC_DEFAULT_OPUS_MODEL: 'anthropic/claude-opus-4.5',
      },
    },
  },
  {
    id: 'packycode',
    name: 'PackyCode',
    category: 'third_party',
    websiteUrl: 'https://www.packyapi.com',
    apiKeyUrl: 'https://www.packyapi.com/register?aff=cc-switch',
    description: 'PackyCode API 中转服务',
    icon: 'packycode',
    isPartner: true,
    config: {
      env: {
        ANTHROPIC_BASE_URL: 'https://www.packyapi.com',
        ANTHROPIC_AUTH_TOKEN: '',
      },
    },
    endpointCandidates: ['https://www.packyapi.com', 'https://api-slb.packyapi.com'],
  },
  {
    id: 'cubence',
    name: 'Cubence',
    category: 'third_party',
    websiteUrl: 'https://cubence.com',
    apiKeyUrl: 'https://cubence.com/signup?code=CCSWITCH&source=ccs',
    description: 'Cubence API 中转服务',
    icon: 'cubence',
    iconColor: '#000000',
    isPartner: true,
    config: {
      env: {
        ANTHROPIC_BASE_URL: 'https://api.cubence.com',
        ANTHROPIC_AUTH_TOKEN: '',
      },
    },
    endpointCandidates: [
      'https://api.cubence.com',
      'https://api-cf.cubence.com',
      'https://api-dmit.cubence.com',
      'https://api-bwg.cubence.com',
    ],
  },
  {
    id: 'aigocode',
    name: 'AIGoCode',
    category: 'third_party',
    websiteUrl: 'https://aigocode.com',
    apiKeyUrl: 'https://aigocode.com/invite/CC-SWITCH',
    description: 'AIGoCode API 中转服务',
    icon: 'aigocode',
    iconColor: '#5B7FFF',
    isPartner: true,
    config: {
      env: {
        ANTHROPIC_BASE_URL: 'https://api.aigocode.com',
        ANTHROPIC_AUTH_TOKEN: '',
      },
    },
  },
  {
    id: 'rightcode',
    name: 'RightCode',
    category: 'third_party',
    websiteUrl: 'https://www.right.codes',
    apiKeyUrl: 'https://www.right.codes/register?aff=CCSWITCH',
    description: 'RightCode API 中转服务',
    icon: 'rc',
    iconColor: '#E96B2C',
    isPartner: true,
    config: {
      env: {
        ANTHROPIC_BASE_URL: 'https://www.right.codes/claude',
        ANTHROPIC_AUTH_TOKEN: '',
      },
    },
  },
  {
    id: 'aicodemirror',
    name: 'AICodeMirror',
    category: 'third_party',
    websiteUrl: 'https://www.aicodemirror.com',
    apiKeyUrl: 'https://www.aicodemirror.com/register?invitecode=9915W3',
    description: 'AICodeMirror API 中转服务',
    icon: 'aicodemirror',
    iconColor: '#000000',
    isPartner: true,
    config: {
      env: {
        ANTHROPIC_BASE_URL: 'https://api.aicodemirror.com/api/claudecode',
        ANTHROPIC_AUTH_TOKEN: '',
      },
    },
    endpointCandidates: [
      'https://api.aicodemirror.com/api/claudecode',
      'https://api.claudecode.net.cn/api/claudecode',
    ],
  },
]

// 根据 ID 获取预设
export function getClaudePreset(id: string): ClaudeProviderPreset | undefined {
  return claudeProviderPresets.find((p) => p.id === id)
}

// 根据分类获取预设列表
export function getClaudePresetsByCategory(category: string): ClaudeProviderPreset[] {
  return claudeProviderPresets.filter((p) => p.category === category)
}
